# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e11eed483a7eb9f02b075b121d7be11cbb9fa00b683241d779e738a23108872a533d15628ca6ef6b4885f387db3f8399c52ca546717daa4d80ed55304513772b

test:
  secret_key_base: 86336dabb32765afdf9bfe96fe6649a98bdb982a64e629e09bbc1fe54b2e914d11c021bd9b07537bd3e108820775f8a7dfe39231570a89053f6a281406289f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
